apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  # Base64 alrare@hotmail.com
  PG_USER_EMAIL: YWxyYXJlQGhvdG1haWwuY29t
  
  # Base64 secretpass
  DB_PASS: c2VjcmV0cGFzcw==